### ISSUE TITLE
setup instructions

### ISSUE THREAD

**Issue by macool** [noggalito/porttare-frontend#4]
should be in the readme

**Comment by macool** [comment]
![screen shot 2016-06-15 at 12 20 33 pm](https://cloud.githubusercontent.com/assets/1407000/16090152/e9366922-32f3-11e6-8ae9-b76658f883a1.png)
un puto readme

**Comment by macool** [comment]
qué carajos significa? ^

**Comment by fabricioflores** [comment]
no puedes dar un trace más amplio? con una línea no sabría decirte

**Comment by macool** [comment]
@fabricioflores sólo hace `$ grunt serve`

**Comment by fabricioflores** [comment]
solved
